services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DATABASE: app
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql

volumes:
  psql:
